### ISSUE TITLE
Create alarm for webmaker-profile-2

### ISSUE THREAD

**Issue by simonwex** [mozilla/webmaker-profile-2#144]
We had some downtime due to a configuration error with webmaker-profile-2. We weren't notified on 503 errors until a user filed a bug.

![image](https://cloud.githubusercontent.com/assets/25260/5649576/d023c592-964b-11e4-975d-95c6afa8bf0b.png)

**Comment by simonwex** [comment]
@jdotpz any progress on this?

**Comment by jdotpz** [comment]
Yeah, this was done a while ago, sorry for not changing the status here!

http://opsview.mofoprod.net:3000/cgi-bin/extinfo.cgi?type=2&service=healthcheck&host=Webmaker-Profile2
