### ISSUE TITLE
Implement Automated Testing

### ISSUE THREAD

**Issue by simonwex** [mozilla/webmaker-profile-2#149]
* [x] Implement testing framework
* [x] Pick two recent or open bugs
  *  Bug: #91 
  *  Bug: #102 
* [x] implement tests that validate fixes for two open bugs
* [x] Document how to add a new test
* [x] Set up project on TravisCI
* [x] Add Travis status Image to README
* [x] Add mofo-style linter
* [x] Ensure all tests are passing

https://github.com/MozillaFoundation/plan/issues/351

**Comment by gvn** [comment]
![clear](https://cloud.githubusercontent.com/assets/206379/6738246/0be0b88c-ce2e-11e4-8a02-0af27fb200ed.gif)
